USE [G1Northwind]
GO

INSERT INTO [dbo].[G1Categorias]
           ([Nombre_Categoria]
           ,[Descripcion])
     VALUES
('bebidas','refrescantes y dulces' ),
('jardin','todo para su patio'),
('automotriz','todo para su vehiculo'),
('mariscos','comida maritima frescas'),
('cereales','cereal de maiz y granola'),
('especias','especias don julio'),
('verduras','frescas y deliciosas'),
('hogar', 'calidad y precio'),
('electricidad', 'foco siempre alerta'),
('construccion','todo lo que necesita'),
('fontaneria','sin fugas en ningun lugar'),
('herraje','para que no te quedes afuer'),
('herr electricas','todo para su mantenimiento'),
('jardineria','todo para el jardin'),
('lamparas','que no se te queme el foco'),
('loza','para tu trono lo mas comodo'),
('ceramica','variedad y calidad garantizada'),
('mascotas','para el consentido de 4 patas'),
('papeleria','todo en utiles escolaras'),
('pinturas','para ese artista que llevas dentro'),
('tecnologia','lo ultimo en la vanguardia tecnologica'),
('navidad','para esas celebraciones especiales'),
('aborroteria','todo lo que necesite en abarroteria'),
('abrillantadores','para tu auto consentido'),
('pastas','todo tipo de pastas al mejor precio'),
('acc automoviles','para consentir a tu bebe de 8 cilindros'),
('Aceites','calidad y densidad de alta calidad'),
('grasas','animal y vegetal'),
('alfombras','de todos los tipos'),
('revestimientos','de todo tipo y calidad'),
('aromatizantes','para eliminar el mal olor'),
('Inversor poten','para todo uso'),
('art limpieza','versatilidad al alcance de su bolsillo'),
('art  medicion', 'calidad garantizada'),
('aspiradoras','potencia y precio al alcance de su mano'),
('baterias','de todo tipo y todas las categorias'),
('infladores','bombas para todo tipo de transporte y mas'),
('bombas trasegar','de agua y de aire'),
('bombillos','para todo tipo de autos'),
('cintas adhesiv','calidad superior'),
('extintores','para todo tipo de situaciones'),
('fusibles bujias','para que no te vuelva a apagar el foco'),
('gatos hidraulic','para que no te quedes vendido a mitad de la calle'),
('guantes','para todo tipo de situaciones'),
('herr neumaticas','todo para cualquier emergencia'),
('jugos','para todas las edades'),
('cafe y azucares','indispensable en tu hogar'),
('cereales grano','para empezar bien el dia'),
('frijoles','indespensable en la dieta nacional'),
('Arroz','indispensable en la dieta nacional'),
('harinas','para el italiano que llevas dentro'),
('pastas', 'para el italiano que llevas dentro'),
('Leche', 'leyde calidad superior'),
('Malteadas','ricas y nutritivas'),
('limpieza','todo para el hogar'),
('mantequilla','calidad superior'),
('aceites','de todos los tipos existentes'),
('panaderia','de todas las harinas disponibles'),
('tortillas','hechas con amor'),
('salsas aderezos','calidad garantizada'),
('snacks','para tus antojitos nocturnos'),
('sopas y cremas','de todos los sabores existentes'),
('abonos','para el cuidado de tus plantas'),
('fertilizantes','tus plantas te lo agradeceran'),
('acampar','saca tu espiritu aventurero'),
('pesca','para los amantes del buen gusto'),
('acc acampar','todo lo que necesitas en un solo lugar'),
('acc jardin','lo ultimo en belleza jardinera'),
('acc bicicleta','que esas ruedas marquen historia'),
('acc manguera','para estar full equipados'),
('aceite antorcha','para que la luz no te de una mala sorpresa'),
('aditivo piscina','para tu toque personal divertido'),
('adornos jardin','todo lo necesario aqui'),
('antorchas','utiles en muchas situaciones'),
('apaga fuegos','para cualquier emergerncia no deseada'),
('banquetas','para toda la familia'),
('asientos','de todo tipo y calidad garantizada'),
('bombas fumigar','para todo tipo de situaciones'),
('bombas inflar','para peques y grandes'),
('carpas','para variedad de eventos'),
('toldos','para variedad de eventos'),
('lonas accesori','para variedad de eventos'),
('cilindros gas','para variedad'),
('cortagrama','variedad garantizada'),
('engrapadoras','variedad al estilo'),
('clavadoras','calidad de primera mano'),
('fuentes','para ese toque especial'),
('grapas','repuestos de todo tipo'),
('grifos','de todo tipo'),
('valvulas','calidad garantizada'),
('hachas','de todo tipo y calidad'),
('herr multipropo','para todo tipo de situaciones'),
('herr jardineria','se ocupa estar preparado'),
('insencticidas','mata plagas de primera'),
('repelentes','individuo preparado vale por dos'),
('jaulas','de todo tipo y calidad'),
('lamparas techo','para ese toque especial para tu hogar'),
('desinfectantes','limpieza siempre a la mano'),
('maceteras','de todos los tipos que te gustan'),
('machetes','para el olanchano que llevas dentro'),
('mallas alambres','para mejorar tu casa'),
('mesas','calidad indiscutible'),
('mueble exterior','calidad en exteriores'),
('muebles jardin','siempre se necesita uno'),
('navaja cuchillo','para todo tipo de cortes'),
('overoles','para ir preparado'),
('palas','no deja rastro ni de las personas'),
('plantas artific','nunca estan de mas'),
('protec personal','siempre precavido'),
('rastrillo','para limpieza exterior'),
('recipientes','de grandes y bajos'),
('rejillas','para todos los reales'),
('rociadores','potencia tu jardin'),
('aspersores','potencia tu jardin'),
('semillas','de todo tipo'),
('sierras','saca el JSON que llevas dentro'),
('tijeras','potencia tu jardin'),
('sombrillas','para situaciones imprevistas'),
('ahuyentadores','para esas plagas indeseadas'),
('azulejo','toque especial indiscutible'),
('bañeras','calidad insuperable'),
('grifos valvulas','sostenibilidad a largo plazo'),
('Inodoros','para el trono de su majestad'),
('lavabos','calidad siempre a su alcance'),
('lavamanos','uselo sabiamente'),
('molduras acc','repuestos de calidad'),
('muebles baños','comodidad y belleza'),
('porcelanato','belleza y calidad juntas'),
('juguet mascotas','para su consentido mamifero'),
('collares','de todo tipo'),
('pecheras','calidad garantizada'),
('alimen mascotas','para todo tipo'),
('acc oficina','calidad de legitima procedencia'),
('tableros','de todo tipo y color'),
('sobres','calidad al alcance de sus manos'),
('perchero gancho','especiales para el regreso a clases'),
('arte manualida','saca el artista que llevas dentro'),
('art medicion','para arquitectos y amantes de las medidad'),
('art dibujar','saca a tu infante interior'),
('art fiesta','que no te agarre desprevenido'),
('pulidora piso','para acabados mas brillantes'),
('basculas','hecho a la medida'),
('balanzas','hecho a la medida'),
('cajas','siempre listas'),
('carretas','a la orden del dia'),
('cepillos','limpieza la orden del dia'),
('basureros','toda cosa en su lugar'),
('bolsas multiuso','para todo tipo de situacion'),
('esponjas pastes','para la limpieza al dia'),
('cober lavadoras','para mantenerlos limpios'),
('cojines','no te quedes sin el tuyo'),
('cortinas','para consentir tu hogar'),
('acc cortinas','te tenemos cubierto'),
('cuadros','para inmortalizar tus momentos'),
('retatreras','para inmortalizar tus momentos'),
('adornos pared','te tenemos cubierto'),
('delantales','para la cocina al dia'),
('toallas','te tenemos cubierto'),
('electrodomestic','todo lo que necesites'),
('escobas','lo mas practico'),
('escuadras','para todo los gustos y colores'),
('estufas','indispensable en la cocina'),
('elimina humedad','para todo lo necesario'),
('cilindros gas','todo lo que necesites'), 
('fuentes','todo cubierto comandante'),
('galletas','alguien dijo antojos'),
('lamparas mesa','para un toque mas personal'),
('lavanderia','te tenemos cubierto'),
('manteles','para un toque mas personal'),
('mantas','cubierto a toda hora'),
('maq palomitas','para esos fines de semana'),
('masaje relajaci','porque te lo mereces'),
('molinos','te tenemos cubierto'),
('neveras','todo en frigorificos'),
('hieleras','todo lo que tu cuerpo necesita'),
('termos','te tenemos cubierto'),
('ollas','tu cocina te lo agradecera'),
('frideras','todo para tu cocina'),
('papel higienico','limpieza al alcance de tu mano'),
('papel toalla','te tenemos cubierto'),
('para empaque','todo cubierto master'),
('pelador naranja','necesaria en tu vida al encontrarla'),
('planchadores','indispensable en tu hogar'),
('plasticos','responsables con el ambiente'),
('primero auxilio','te tenmos cubierto'),
('purifi ambiente','tu casa te lo agradecera'),
('recipientes','para todo tipo de liquido'),
('relojes mesa','que no se te pierda la hora'),
('relojes pared','una hora excepcional'),
('reposteria','todo lo que necesites chef'),
('termomet cocina','todo bajo presion'),
('termos alimento','para cuando salgas de casa'),
('termos bebidad','calientes o frias, tu decides'),
('uso personal','todo lo que necesites'),
('vajillas','calidad garantizada'),
('cubiertos','que no te falte nada'),
('varios','de todo un poco'),
('acc hogar','todo lo que necesites en un solo lugar'),
('acc cocina','no te preocupes, te tenemos cubierto')
GO


